# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZeroEye' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZeroEye
    pod 'Parse'
    pod 'MessageInputBar'
  target 'ZeroEyeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZeroEyeUITests' do
    # Pods for testing
  end

end
